/* 
 * File:   statusManager.h
 * Author: michele.abelli
 *
 * Created on 12 marzo 2020, 11.52
 */

#ifndef STATUSMANAGER_H
#define	STATUSMANAGER_H

enum {
	/* 0 */   TINTING_INIT_ST=0,
	/* 1 */   TINTING_READY_ST,
	/* 2 */   TINTING_MIXER_SEARCH_HOMING_ST,
	/* 3 */   TINTING_HOMING_ST,
	/* 4 */   TINTING_SUPPLY_END_ST,
	/* 5 */   TINTING_SUPPLY_RUN_ST,
	/* 6 */   TINTING_PAR_RX,
	/* 7 */   TINTING_JUMP_TO_BOOT, 
	/* 8 */   TINTING_STOP_ST, 
	/* 9 */   TINTING_WAIT_PARAMETERS_ST,
	/* 10 */  TINTING_WAIT_MIXER_PARAMETERS_ST,
	/* 11 */  TINTING_WAIT_SETUP_OUTPUT_ST,  
	/* 12 */  TINTING_MIXER_TEST_ST, 
    /* 13 */  TINTING_SETUP_OUTPUT_MIXER_ST,
    /* 14 */  TINTING_SETUP_OUTPUT_ST, 
    /* 15 */  TINTING_JAR_MOTOR_RUN_ST,
    /* 16 */  TINTING_JAR_MOTOR_END_ST,
    /* 17 */  TINTING_SET_HIGH_CURRENT_MIXER_MOTOR_RUN_ST,
    /* 18 */  TINTING_SET_HIGH_CURRENT_MIXER_MOTOR_END_ST,
    /* 19 */  TINTING_AUTOCAP_SEARCH_HOMING_ST,
    /* 20 */  TINTING_AUTOCAP_PACKING_ST,
    /* 21 */  TINTING_AUTOCAP_PACKING_END_ST,
    /* 22 */  TINTING_AUTOCAP_OPEN_ST,
    /* 23 */  TINTING_AUTOCAP_CLOSE_ST, 
    /* 24 */  TINTING_AUTOCAP_EXTEND_ST, 
    /* 25 */  TINTING_AUTOCAP_RETRACT_ST, 
    /* 26 */  TINTING_AUTOCAP_OPEN_RUN_ST,
    /* 27 */  TINTING_AUTOCAP_CLOSE_RUN_ST,
    /* 28 */  TINTING_AUTOCAP_EXTEND_RUN_ST,
    /* 29 */  TINTING_MIXING_OPEN_DOOR,        
    /* 30 */  TINTING_MIXING_OPEN_DOOR_END,        
              
  /** Errors */
    /* 50 */  TINTING_TIMEOUT_ERROR_ST = 50, 
    /* 51 */  TINTING_MIXER_JAR_PHOTO_READ_LIGHT_ERROR_ST,
    /* 52 */  TINTING_MIXER_JAR_PHOTO_READ_DARK_ERROR_ST,
    /* 53 */  TINTING_MIXER_PHOTO_READ_LIGHT_ERROR_ST,
    /* 54 */  TINTING_MIXER_PHOTO_READ_DARK_ERROR_ST, 
    /* 55 */  TINTING_MIXER_RESET_ERROR_ST,
    /* 56 */  TINTING_MIXER_TEST_ERROR_ST,     
    /* 57 */  TINTING_RH_ERROR_ST,
    /* 58 */  TINTING_TEMPERATURE_ERROR_ST,     
    /* 59 */  TINTING_MIXER_SOFTWARE_ERROR_ST,
    /* 60 */  TINTING_BAD_PAR_HUMIDIFIER_ERROR_ST,
    /* 61 */  TINTING_BAD_PAR_MIXER_ERROR_ST,
    /* 62 */  TINTING_BAD_PERIPHERAL_PARAM_ERROR_ST, 
    /* 63 */  TINTING_MIXER_HOMING_ERROR_ST,
    /* 64 */  TINTING_NEBULIZER_OPEN_LOAD_ERROR_ST,
    /* 65 */  TINTING_NEBULIZER_OVERCURRENT_THERMAL_ERROR_ST,
    /* 66 */  TINTING_RELE_OPEN_LOAD_ERROR_ST,
    /* 67 */  TINTING_RELE_OVERCURRENT_THERMAL_ERROR_ST, 
    /* 68 */  TINTING_GENERIC24V_OPEN_LOAD_ERROR_ST,
    /* 69 */  TINTING_GENERIC24V_OVERCURRENT_THERMAL_ERROR_ST,              
    /* 70 */  TINTING_MIXER_MOTOR_THERMAL_SHUTDOWN_ERROR_ST,
    /* 71 */  TINTING_MIXER_MOTOR_UNDER_VOLTAGE_ERROR_ST,
    /* 72 */  TINTING_MIXER_MOTOR_OVERCURRENT_ERROR_ST,
    /* 73 */  TINTING_MIXER_MOTOR_BLOCKED_ERROR_ST,
    /* 74 */  TINTING_MIXER_DOOR_MICROSWITCH_OPEN_ERROR_ST,
    /* 75 */  TINTING_MIXER_DOOR_MICROSWITCH_CLOSE_ERROR_ST,
    /* 76 */  TINTING_DOOR_MOTOR_THERMAL_SHUTDOWN_ERROR_ST,
    /* 77 */  TINTING_DOOR_MOTOR_UNDER_VOLTAGE_ERROR_ST,
    /* 78 */  TINTING_DOOR_MOTOR_OVERCURRENT_ERROR_ST,
    /* 79 */  TINTING_DOOR_MOTOR_BLOCKED_ERROR_ST,   
    /* 80 */  TINTING_MIXER_DOOR_OPEN_PHOTO_READ_LIGHT_ERROR_ST,
    /* 81 */  TINTING_MIXER_DOOR_OPEN_PHOTO_READ_DARK_ERROR_ST, 
    /* 82 */  TINTING_TIMEOUT_JAR_PRESENCE_ERROR_ST, 
    /* 83 */  TINTING_MIXER_MOTOR_HIGH_CURRENT_NOT_SETTED_ST,
    /* 84 */  MIXER_TOO_LOW_WATER_LEVEL_ST,
    /* 85 */  TINTING_AIR_PUMP_OVERCURRENT_THERMAL_ERROR_ST,
    /* 86 */  TINTING_AIR_PUMP_OPEN_LOAD_ERROR_ST,
    /* 87 */  TINTING_AUTOCAP_HOMING_ERROR_ST, 
    /* 88 */  TINTING_AUTOCAP_MOTOR_OVERCURRENT_ERROR_ST,
    /* 89 */  TINTING_AUTOCAP_MOTOR_UNDER_VOLTAGE_ERROR_ST,
    /* 90 */  TINTING_AUTOCAP_MOTOR_THERMAL_SHUTDOWN_ERROR_ST,
    /* 91 */  TINTING_AUTOCAP_PACKING_ERROR_ST,
    /* 92 */  TINTING_AUTOCAP_SOFTWARE_ERROR_ST,
    /* 94 */  TINTING_AUTOCAP_LIFTER_ERROR_ST,
    /* 96 */  TINTING_AUTOCAP_HOME_POS_ERROR_ST,
    /* 97 */  TINTING_AUTOCAP_DRV_OVER_CURR_TEMP_ERROR_ST,
};

enum {
    CMD_TINTING_IDLE    = 0x00,
    CMD_TINTING_STOP    = 0x01,
    CMD_TINTING_INTR    = 0x02,
    CMD_TINTING_HOME    = 0x04,
    CMD_TINTING_PACKING = 0x08,
    CMD_TINTING_OPEN    = 0x10,
    CMD_TINTING_CLOSE   = 0x20,
    CMD_TINTING_EXTEND  = 0x40,
    CMD_TINTING_RETRACT = 0x80,
  };
  
enum {
    CONTROLLO_PRESENZA = 0x01,
    POS_HOMING = 0x02,
    POSIZIONA_AUTOCAP  = 0x0D,
    SETUP_PARAMETRI_UMIDIFICATORE = 0x13,
    JUMP_TO_BOOT = 0x15,
    MISCELAZIONE_PRODOTTO = 0x22,
    SETUP_PARAMETRI_MIXER  = 0x23,
    TEST_FUNZIONAMENTO_MIXER = 0x24,
    IMPOSTA_USCITE_MIXER = 0x25,    
    USCITA_BARATTOLO = 0x26,
    IMPOSTA_CORRENTE_MANTENIMENTO_MOTORE_MIXER = 0x27,
    MISCELAZIONE_USCITA_BARATTOLO = 0x28,
  };
  
enum {
  STEP_0,  STEP_1,  STEP_2,  STEP_3,  STEP_4,
  STEP_5,  STEP_6,  STEP_7,  STEP_8,  STEP_9,
  STEP_10, STEP_11, STEP_12, STEP_13, STEP_14,
  STEP_15, STEP_16, STEP_17, STEP_18, STEP_19,
  STEP_20, STEP_21, STEP_22, STEP_23, STEP_24,
  STEP_25, STEP_26, STEP_27, STEP_28, STEP_29,
  STEP_30, STEP_31, STEP_32, STEP_33, STEP_34,
  STEP_35, STEP_36, STEP_37, STEP_38, STEP_39,
  STEP_40, STEP_41, STEP_42, STEP_43, STEP_44,
  STEP_45, STEP_46, STEP_47, STEP_48, STEP_49,
  STEP_50, STEP_51, STEP_52, STEP_53, STEP_54,
};

extern void StatusManager(void);
extern void initStatusManager(void);
extern void initParam(void);
extern void jump_to_boot(void);
extern void visualIndicator(void);

#endif	/* STATUSMANAGER_H */

